/**
 * Replaces public/sw.js with a no-op service worker for local development.
 * Run automatically via the "dev" npm script so stale production SW manifests
 * don't break the dev server with 404 precache errors.
 *
 * The real SW is regenerated by `npm run build` (Serwist / @serwist/next).
 */

const fs   = require('fs');
const path = require('path');

const swPath = path.join(__dirname, '..', 'public', 'sw.js');

const noop = `// dev mode — clears all caches and unregisters this SW
self.addEventListener('install', e => {
  e.waitUntil(
    caches.keys().then(keys => Promise.all(keys.map(k => caches.delete(k))))
  );
  self.skipWaiting();
});
self.addEventListener('activate', e => {
  e.waitUntil(
    clients.matchAll({ type: 'all', includeUncontrolled: true })
      .then(cs => { cs.forEach(c => c.navigate(c.url)); })
      .then(() => self.registration.unregister())
  );
});
`;

if (fs.existsSync(swPath)) {
  fs.writeFileSync(swPath, noop, 'utf8');
  console.log('[dev-sw] Replaced public/sw.js with dev no-op (clears caches + unregisters)');
} else {
  console.log('[dev-sw] public/sw.js not found, skipping');
}
