import type { OrganizationType, Role } from '@/types'

export interface NavItem {
  to: string
  label: string
  icon: string
  section?: string
  /** When set, only show for institutions of this type. */
  orgType?: OrganizationType
}

export const NAV: Record<Role, NavItem[]> = {
  student: [
    { to: '/student', label: 'Dashboard', icon: '◉' },
    { to: '/student/profile', label: 'My Profile', icon: '👤' },
    { to: '/student/academic', label: 'Academic', icon: '📈', section: 'Learning' },
    { to: '/student/courses', label: 'Courses', icon: '📚' },
    { to: '/student/schedule', label: 'Schedule', icon: '🗓' },
    { to: '/student/attendance', label: 'Attendance', icon: '✓' },
    { to: '/student/report-cards', label: 'Report Cards', icon: '🧾' },
    { to: '/student/reports', label: 'Reports', icon: '📄' },
    { to: '/student/finance', label: 'Fees & Invoices', icon: '💳' },
    { to: '/student/credentials', label: 'Credentials', icon: '🎖' },
    { to: '/student/mentors', label: 'Mentors', icon: '🧭', section: 'Support' },
    { to: '/student/requests', label: 'Requests', icon: '📨' },
    { to: '/student/documents', label: 'Documents', icon: '🗂' },
    { to: '/student/messages', label: 'Messages', icon: '💬' },
    { to: '/student/notifications', label: 'Notifications', icon: '🔔' },
    { to: '/student/settings', label: 'Settings', icon: '⚙', section: 'Account' },
  ],
  teacher: [
    { to: '/teacher', label: 'Dashboard', icon: '◉' },
    { to: '/teacher/students', label: 'Students', icon: '🎓', section: 'Teaching' },
    { to: '/teacher/classes', label: 'Classes', icon: '🏫' },
    { to: '/teacher/schedule', label: 'Schedule', icon: '🗓' },
    { to: '/teacher/attendance', label: 'Attendance', icon: '✓' },
    { to: '/teacher/gradebook', label: 'Gradebook', icon: '📊' },
    { to: '/teacher/reports', label: 'Reports', icon: '📄' },
    { to: '/teacher/mentorship', label: 'Mentorship', icon: '🧭', section: 'Mentoring' },
    { to: '/teacher/resources', label: 'Resources', icon: '📦' },
    { to: '/teacher/announcements', label: 'Announcements', icon: '📢' },
    { to: '/teacher/messages', label: 'Messages', icon: '💬', section: 'Account' },
    { to: '/teacher/notifications', label: 'Notifications', icon: '🔔' },
    { to: '/teacher/profile', label: 'Profile', icon: '👤' },
    { to: '/teacher/settings', label: 'Settings', icon: '⚙' },
  ],
  mentor: [
    { to: '/teacher', label: 'Dashboard', icon: '◉' },
    { to: '/teacher/mentorship', label: 'Mentorship', icon: '🧭' },
    { to: '/teacher/students', label: 'Mentees', icon: '🎓' },
    { to: '/teacher/reports', label: 'Reports', icon: '📄' },
    { to: '/teacher/messages', label: 'Messages', icon: '💬' },
    { to: '/teacher/notifications', label: 'Notifications', icon: '🔔' },
    { to: '/teacher/settings', label: 'Settings', icon: '⚙' },
  ],
  school: [
    { to: '/school', label: 'Dashboard', icon: '◉' },
    { to: '/school/profile', label: 'Institution Profile', icon: '🏛' },
    { to: '/school/students', label: 'Students', icon: '🎓', section: 'People' },
    { to: '/school/teachers', label: 'Teachers', icon: '👩‍🏫' },
    { to: '/school/mentors', label: 'Mentors', icon: '🧭' },
    { to: '/school/transfers', label: 'Transfers', icon: '🔁' },
    { to: '/school/record-requests', label: 'Records Requests', icon: '📥' },
    { to: '/school/credentials', label: 'Credentials', icon: '🎖' },
    { to: '/school/admissions', label: 'Admissions', icon: '📝', section: 'Academics' },
    { to: '/school/classes', label: 'Classes', icon: '🏫' },
    { to: '/school/subjects', label: 'Subjects', icon: '📘' },
    { to: '/school/timetable', label: 'Timetable', icon: '🗓' },
    { to: '/school/programs', label: 'Faculties & Programs', icon: '🎓', orgType: 'UNIVERSITY' },
    { to: '/school/attendance', label: 'Attendance', icon: '✓' },
    { to: '/school/academic', label: 'Academic Records', icon: '📊' },
    { to: '/school/grading', label: 'Grading Schemes', icon: '⚖️' },
    { to: '/school/report-cards', label: 'Report Cards', icon: '🧾' },
    { to: '/school/interventions', label: 'Interventions', icon: '🚩' },
    { to: '/school/guardians', label: 'Guardians', icon: '👪' },
    { to: '/school/finance', label: 'Finance', icon: '💰', section: 'Operations' },
    { to: '/school/import', label: 'Bulk Import', icon: '📤' },
    { to: '/school/year-end', label: 'Year-End', icon: '🎓' },
    { to: '/school/reports', label: 'Reports', icon: '📄' },
    { to: '/school/documents', label: 'Documents', icon: '🗂' },
    { to: '/school/announcements', label: 'Announcements', icon: '📢' },
    { to: '/school/government', label: 'Government', icon: '🏢' },
    { to: '/school/campaigns', label: 'Data Campaigns', icon: '📋' },
    { to: '/school/messages', label: 'Messages', icon: '💬', section: 'Account' },
    { to: '/school/audit', label: 'Audit Log', icon: '🛡' },
    { to: '/school/settings', label: 'Settings', icon: '⚙' },
  ],
  guardian: [
    { to: '/guardian', label: 'Overview', icon: '◉' },
    { to: '/guardian/children', label: 'My Children', icon: '👨‍👩‍👧' },
    { to: '/guardian/finance', label: 'Fees & Invoices', icon: '💳' },
    { to: '/guardian/messages', label: 'Messages', icon: '💬', section: 'Account' },
    { to: '/guardian/notifications', label: 'Notifications', icon: '🔔' },
    { to: '/guardian/settings', label: 'Settings', icon: '⚙' },
  ],
  government: [
    { to: '/government', label: 'Dashboard', icon: '◉' },
    { to: '/government/schools', label: 'Institutions', icon: '🏫', section: 'Oversight' },
    { to: '/government/institutions', label: 'Registry', icon: '🏛' },
    { to: '/government/analytics', label: 'Analytics', icon: '📊' },
    { to: '/government/reports', label: 'Reports', icon: '📄' },
    { to: '/government/requests', label: 'Request Center', icon: '📨', section: 'Casework' },
    { to: '/government/campaigns', label: 'Data Campaigns', icon: '📋' },
    { to: '/government/authorize', label: 'Authorize Institutions', icon: '✅' },
    { to: '/government/announcements', label: 'Announcements', icon: '📢' },
    { to: '/government/documents', label: 'Documents', icon: '🗂' },
    { to: '/government/messages', label: 'Messages', icon: '💬', section: 'Account' },
    { to: '/government/audit', label: 'Audit Log', icon: '🛡' },
    { to: '/government/settings', label: 'Settings', icon: '⚙' },
  ],
  admin: [
    { to: '/admin', label: 'Dashboard', icon: '◉' },
    { to: '/admin/organizations', label: 'Institutions', icon: '🏛', section: 'Onboarding' },
    { to: '/admin/invitations', label: 'Invitations', icon: '✉' },
    { to: '/admin/users', label: 'Users', icon: '👥', section: 'Directory' },
    { to: '/admin/students', label: 'Students', icon: '🎓' },
    { to: '/admin/teachers', label: 'Teachers', icon: '👩‍🏫' },
    { to: '/admin/mentors', label: 'Mentors', icon: '🧭' },
    { to: '/admin/schools', label: 'Institution Registry', icon: '🏫' },
    { to: '/admin/government', label: 'Government', icon: '🏛' },
    { to: '/admin/reports', label: 'Reports', icon: '📄', section: 'Oversight' },
    { to: '/admin/requests', label: 'Requests', icon: '📨' },
    { to: '/admin/content', label: 'Content', icon: '📢' },
    { to: '/admin/notifications', label: 'Notifications', icon: '🔔' },
    { to: '/admin/audit', label: 'Audit Logs', icon: '🛡', section: 'System' },
    { to: '/admin/system', label: 'System Health', icon: '🖥' },
    { to: '/admin/backups', label: 'Backups', icon: '💾' },
    { to: '/admin/settings', label: 'Settings', icon: '⚙' },
  ],
}

export const ROLE_LABEL: Record<Role, string> = {
  student: 'Student',
  teacher: 'Teacher / Mentor',
  mentor: 'Mentor',
  guardian: 'Parent / Guardian',
  school: 'School Administration',
  government: 'Government',
  admin: 'Platform Administrator',
}

export const ROLE_HOME: Record<Role, string> = {
  student: '/student',
  teacher: '/teacher',
  mentor: '/teacher',
  guardian: '/guardian',
  school: '/school',
  government: '/government',
  admin: '/admin',
}
